export const DIALOGS = {
  liveAgentDialog: 'liveAgentDialog',
  categoryIntelDialog: 'categoryIntelDialog',
  supplierIntelDialog: 'supplierIntelDialog',
  scopeCustomMarketIntelDialog: 'scopeCustomMarketIntelDialog',
  otherDialog: 'otherDialog',
  priceOrCostDialog: 'priceOrCostDialog',
  categoryReportDialog: 'categoryReportDialog',
  categoryInsightsDialog: 'categoryInsightsDialog',
  globalDataDialog: 'globalDataDialog',
  benchMarkDialog: 'benchMarkDialog',
  regionDialog: 'regionDialog',
  supplierShortlistDialog: 'supplierShortlistDialog',
  supplierRiskRatingDialog: 'supplierRiskRatingDialog',
  supplierDetailsDialog: 'supplierDetailsDialog',
  requestDemoDialog: 'requestDemoDialog',
  upgradeSubscriptionDialog: 'upgradeSubscriptionDialog',
  accessIssueDialog: 'accessIssueDialog',
  customizedMarketIntelligenceDialog: 'customizedMarketIntelligenceDialog',
  scopeCustomMarketSupplierShortlisting: 'scopeCustomMarketSupplierShortlisting',
  mainWaterfallDialog: 'mainWaterfallDialog',
  submitHardwareDialog: 'submitHardwareDialog',
  logDefectiveHardwareDialog: 'logDefectiveHardwareDialog',
  assignHardwareDialog: 'assignHardwareDialog',
  replaceHardwareDialog: 'replaceHardwareDialog',
  newHardwareDialog: 'newHardwareDialog',
};
